const COUNTRIES_DATA = [
  {
    "id": "japan",
    "name": "日本",
    "flag": "🇯🇵",
    "capital": "東京",
    "region": "asia",
    "mapX": 84,
    "mapY": 38,
    "iso": "jp",
    "trivia": "島国で、新幹線や桜、富士山が有名。戦国時代のシミュレーションゲームで織田信長や武田信玄が人気だよ！"
  },
  {
    "id": "usa",
    "name": "アメリカ",
    "flag": "🇺🇸",
    "capital": "ワシントンD.C.",
    "region": "americas",
    "mapX": 20,
    "mapY": 35,
    "iso": "us",
    "trivia": "自由の女神やディズニー、NASAがある国。世界最大級のゲーム会社やパソコンの技術も最先端だよ。"
  },
  {
    "id": "china",
    "name": "中国",
    "flag": "🇨🇳",
    "capital": "北京",
    "region": "asia",
    "mapX": 76,
    "mapY": 38,
    "iso": "cn",
    "trivia": "世界で最も人口が多い国の一つ。万里の長城があり、三国志のシミュレーションゲームの舞台として大人気！"
  },
  {
    "id": "uk",
    "name": "イギリス",
    "flag": "🇬🇧",
    "capital": "ロンドン",
    "region": "europe",
    "mapX": 45,
    "mapY": 26,
    "iso": "gb",
    "trivia": "ビッグベンやハリーポッター、シャーロックホームズの国。大航海時代を代表する強力な海軍を持っていたよ。"
  },
  {
    "id": "france",
    "name": "フランス",
    "flag": "🇫🇷",
    "capital": "パリ",
    "region": "europe",
    "mapX": 47,
    "mapY": 31,
    "iso": "fr",
    "trivia": "エッフェル塔やルーブル美術館がある芸術の国。ナポレオン皇帝がヨーロッパ中に遠征した歴史があるよ。"
  },
  {
    "id": "germany",
    "name": "ドイツ",
    "flag": "🇩🇪",
    "capital": "ベルリン",
    "region": "europe",
    "mapX": 49,
    "mapY": 29,
    "iso": "de",
    "trivia": "自動車づくりやソーセージ、城（ノイシュヴァンシュタイン城）が有名。ボードゲームの聖地でもあるよ。"
  },
  {
    "id": "italy",
    "name": "イタリア",
    "flag": "🇮🇹",
    "capital": "ローマ",
    "region": "europe",
    "mapX": 49,
    "mapY": 33,
    "iso": "it",
    "trivia": "ピザやパスタ発祥の地。古代ローマ帝国の歴史があり、コロッセオなどロマンあふれる遺跡が多い国。"
  },
  {
    "id": "india",
    "name": "インド",
    "flag": "🇮🇳",
    "capital": "ニューデリー",
    "region": "asia",
    "mapX": 71,
    "mapY": 48,
    "iso": "in",
    "trivia": "カレーの本場。IT技術や数学が非常に発達している国。数字の「0」を発見したのは古代インドの数学者だよ！"
  },
  {
    "id": "egypt",
    "name": "エジプト",
    "flag": "🇪🇬",
    "capital": "カイロ",
    "region": "africa",
    "mapX": 54,
    "mapY": 45,
    "iso": "eg",
    "trivia": "巨大なピラミッドやスフィンクス、砂漠が広がる古代文明の国。歴史シミュレーションゲームの定番だね！"
  },
  {
    "id": "brazil",
    "name": "ブラジル",
    "flag": "🇧🇷",
    "capital": "ブラジリア",
    "region": "americas",
    "mapX": 33,
    "mapY": 65,
    "iso": "br",
    "trivia": "広大なアマゾン川と熱帯雨林がある国。サッカーがとても盛んで、情熱的なサンバカーニバルが有名。"
  },
  {
    "id": "australia",
    "name": "オーストラリア",
    "flag": "🇦🇺",
    "capital": "キャンベラ",
    "region": "oceania",
    "mapX": 82,
    "mapY": 75,
    "iso": "au",
    "trivia": "南半球にある巨大な島国。コアラやカンガルー、カモノハシなど、独自の進化を遂げた動物がいっぱい！"
  },
  {
    "id": "canada",
    "name": "カナダ",
    "flag": "🇨🇦",
    "capital": "オタワ",
    "region": "americas",
    "mapX": 20,
    "mapY": 20,
    "iso": "ca",
    "trivia": "世界で2番目に広い国。美しいメープルシロップや大自然、夜にはオーロラが見られることで有名だよ。"
  },
  {
    "id": "russia",
    "name": "ロシア",
    "flag": "🇷🇺",
    "capital": "モスクワ",
    "region": "asia",
    "mapX": 66,
    "mapY": 22,
    "iso": "ru",
    "trivia": "世界で最も面積が広い国。極寒のシベリア大地が広がり、テトリスというゲームが生まれた国でもあるよ。"
  },
  {
    "id": "kenya",
    "name": "ケニア",
    "flag": "🇰🇪",
    "capital": "ナイロビ",
    "region": "africa",
    "mapX": 56,
    "mapY": 57,
    "iso": "ke",
    "trivia": "サバンナが広がり、ライオンやゾウが野生で暮らす国。野生動物サファリのシミュレーションだ！"
  },
  {
    "id": "south_africa",
    "name": "南アフリカ",
    "flag": "🇿🇦",
    "capital": "プレトリア",
    "region": "africa",
    "mapX": 53,
    "mapY": 72,
    "iso": "za",
    "trivia": "ペンギンが住むビーチや金山、ダイヤモンド鉱山があるアフリカ南端の国。大自然が豊かだよ。"
  },
  {
    "id": "korea",
    "name": "韓国",
    "flag": "🇰🇷",
    "capital": "ソウル",
    "region": "asia",
    "mapX": 81,
    "mapY": 38,
    "iso": "kr",
    "trivia": "美味しい焼肉やキムチ、K-POPの国。eスポーツ（ゲームの大会）が非常に盛んなことで知られているよ。"
  },
  {
    "id": "singapore",
    "name": "シンガポール",
    "flag": "🇸🇬",
    "capital": "シンガポール",
    "region": "asia",
    "mapX": 76,
    "mapY": 54,
    "iso": "sg",
    "trivia": "マーライオンの石像がある、東南アジアのとても綺麗でハイテクな都市国家。貿易の重要な中継地点だよ。"
  },
  {
    "id": "spain",
    "name": "スペイン",
    "flag": "🇪🇸",
    "capital": "マドリード",
    "region": "europe",
    "mapX": 45,
    "mapY": 34,
    "iso": "es",
    "trivia": "サグラダ・ファミリア教会やフラメンコ、闘牛の国。大航海時代にコロンブスを派遣して世界に進出したよ。"
  },
  {
    "id": "switzerland",
    "name": "スイス",
    "flag": "🇨🇭",
    "capital": "ベルン",
    "region": "europe",
    "mapX": 48,
    "mapY": 31,
    "iso": "ch",
    "trivia": "アルプスの少女ハイジの舞台。美しいアルプス山脈と湖があり、永世中立国として平和な国だよ。"
  },
  {
    "id": "greece",
    "name": "ギリシャ",
    "flag": "🇬🇷",
    "capital": "アテネ",
    "region": "europe",
    "mapX": 51,
    "mapY": 35,
    "iso": "gr",
    "trivia": "ギリシャ神話やオリンピック発祥の地。パルテノン神殿など、白と青の美しいコントラストの街並みが有名。"
  },
  {
    "id": "turkey",
    "name": "トルコ",
    "flag": "🇹🇷",
    "capital": "アンカラ",
    "region": "asia",
    "mapX": 55,
    "mapY": 35,
    "iso": "tr",
    "trivia": "アジアとヨーロッパの架け橋となる国。カッパドキアの気球や、世界三大料理のトルコ料理が有名だよ。"
  },
  {
    "id": "saudi_arabia",
    "name": "サウジアラビア",
    "flag": "🇸🇦",
    "capital": "リヤド",
    "region": "asia",
    "mapX": 59,
    "mapY": 47,
    "iso": "sa",
    "trivia": "中東の広大な砂漠の国。石油がたくさん採れることで知られており、オアシスの都市が発展しているよ。"
  },
  {
    "id": "mexico",
    "name": "メキシコ",
    "flag": "🇲🇽",
    "capital": "メキシコシティ",
    "region": "americas",
    "mapX": 16,
    "mapY": 45,
    "iso": "mx",
    "trivia": "古代マヤ文明・アステカ文明の遺跡がある国。タコスや陽気な音楽、ガイコツを飾る「死者の日」が有名。"
  },
  {
    "id": "argentina",
    "name": "アルゼンチン",
    "flag": "🇦🇷",
    "capital": "ブエノスアイレス",
    "region": "americas",
    "mapX": 29,
    "mapY": 75,
    "iso": "ar",
    "trivia": "サッカー選手メッシの母国。パタゴニアの氷河や、南米のパリと呼ばれる美しい首都があるよ。"
  },
  {
    "id": "new_zealand",
    "name": "ニュージーランド",
    "flag": "🇳🇿",
    "capital": "ウェリントン",
    "region": "oceania",
    "mapX": 87,
    "mapY": 81,
    "iso": "nz",
    "trivia": "羊の数が人口より多いのどかな島国。飛べない鳥「キーウィ」やマオリ族のハカダンスが有名だよ。"
  },
  {
    "id": "mongolia",
    "name": "モンゴル",
    "flag": "🇲🇳",
    "capital": "ウランバートル",
    "region": "asia",
    "mapX": 73,
    "mapY": 32,
    "iso": "mn",
    "trivia": "大草原が広がり、遊牧民が「ゲル」という移動式のテントで暮らす国。かつてチンギス・ハンが世界最大の帝国を築いたよ。"
  },
  {
    "id": "vatican",
    "name": "バチカン",
    "flag": "🇻🇦",
    "capital": "バチカン市国",
    "region": "europe",
    "mapX": 49,
    "mapY": 34,
    "iso": null,
    "trivia": "【極小国・ピン留め】イタリアのローマ市内にある、世界で一番面積が狭い独立国。キリスト教のカトリック総本山だよ。"
  },
  {
    "id": "antarctica",
    "name": "南極地域",
    "flag": "❄️",
    "capital": "なし",
    "region": "oceania",
    "mapX": 50,
    "mapY": 92,
    "iso": null,
    "trivia": "【特別地域・ピン留め】地球で最も寒く、ぶ厚い氷に覆われた地域。国ではなく、ペンギンや観測隊の人たちだけがいる特別な場所だよ。"
  },
  {
    "id": "taiwan",
    "name": "台湾",
    "flag": "🇹🇼",
    "capital": "台北",
    "region": "de_facto",
    "mapX": 79,
    "mapY": 43,
    "iso": "tw",
    "trivia": "【実質上の国】美味しいタピオカや小籠包、夜市が有名。世界最先端の半導体（パソコンの脳みそ）を作る工場がたくさんあるよ！"
  },
  {
    "id": "kosovo",
    "name": "コソボ",
    "flag": "🇽🇰",
    "capital": "プリシュティナ",
    "region": "de_facto",
    "mapX": 50,
    "mapY": 33,
    "iso": null,
    "trivia": "【実質上の国・ピン留め】バルカン半島にある、2008年に独立を宣言した新しい国。歴史的にさまざまな文化が交差する場所だよ。"
  },
  {
    "id": "palestine",
    "name": "パレスチナ",
    "flag": "🇵🇸",
    "capital": "エルサレム(主張)",
    "region": "de_facto",
    "mapX": 56,
    "mapY": 44,
    "iso": null,
    "trivia": "【実質上の国・ピン留め】地中海の東側にある歴史の古い地域。オリーブの木が特産で、古代の遺跡が数多く残っているよ。"
  },
  {
    "id": "western_sahara",
    "name": "西サハラ",
    "flag": "🇪🇭",
    "capital": "アイウン(主張)",
    "region": "de_facto",
    "mapX": 42,
    "mapY": 49,
    "iso": null,
    "trivia": "【実質上の国・ピン留め】アフリカの北西部にあり、広大なサハラ砂漠が広がる地域。大西洋に面しており、リン鉱石や漁業資源が豊富だよ。"
  },
  {
    "id": "greenland",
    "name": "グリーンランド",
    "flag": "🇬🇱",
    "capital": "ヌーク",
    "region": "de_facto",
    "mapX": 35,
    "mapY": 12,
    "iso": "gl",
    "trivia": "【特別地域】世界で最も大きな島。デンマークの領土だけど、実質的に独自の政府を持っているよ。国土のほとんどが氷に覆われているよ。"
  },
  {
    "id": "hong_kong",
    "name": "香港",
    "flag": "🇭🇰",
    "capital": "香港",
    "region": "de_facto",
    "mapX": 78,
    "mapY": 44,
    "iso": null,
    "trivia": "【特別地域・ピン留め】「100万ドルの夜景」と超高層ビル群で有名な高密度都市。かつてはイギリスの領土で、今は中国の特別な地域だよ。"
  },
  {
    "id": "macau",
    "name": "マカオ",
    "flag": "🇲🇴",
    "capital": "マカオ",
    "region": "de_facto",
    "mapX": 77,
    "mapY": 44,
    "iso": null,
    "trivia": "【特別地域・ピン留め】カジノやポルトガル風の古い洋館、世界遺産が有名な地域。香港のすぐ隣に位置するよ。"
  },
  {
    "id": "somaliland",
    "name": "ソマリランド",
    "flag": "🧭",
    "capital": "ハルゲイサ",
    "region": "de_facto",
    "mapX": 58,
    "mapY": 54,
    "iso": "_somaliland",
    "trivia": "【実質上の国】ソマリアの北部が1991年に独立を宣言した地域。国際的には認められていないけれど、独自の通貨や警察を持ち、とても治安が安定しているよ。"
  },
  {
    "id": "northern_cyprus",
    "name": "北キプロス",
    "flag": "🧭",
    "capital": "レフコシャ",
    "region": "de_facto",
    "mapX": 54,
    "mapY": 36,
    "iso": null,
    "trivia": "【実質上の国・ピン留め】地中海に浮かぶキプロス島の北部。トルコだけが国として認めている、歴史的にとてもフクザツな美しい島だよ。"
  },
  {
    "id": "transnistria",
    "name": "沿ドニエストル",
    "flag": "🧭",
    "capital": "ティラスポリ",
    "region": "de_facto",
    "mapX": 51,
    "mapY": 29,
    "iso": null,
    "trivia": "【実質上の国・ピン留め】モルドバとウクライナの境界にある細長い地域。ソビエト連邦時代のシンボル（鎌とハンマー）が今も街中に残っているマニアックな場所だよ。"
  },
  {
    "id": "united_arab_emirates",
    "name": "UAE",
    "flag": "🇦🇪",
    "capital": "アブダビ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "ae",
    "trivia": "【アジアの国】美しいUAEだよ！首都はアブダビ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "afghanistan",
    "name": "アフガニスタン",
    "flag": "🇦🇫",
    "capital": "カブール",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "af",
    "trivia": "【アジア】大航海パズルピース『アフガニスタン』を発見！首都はカブールだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "albania",
    "name": "アルバニア",
    "flag": "🇦🇱",
    "capital": "ティラナ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "al",
    "trivia": "【ヨーロッパの国】アルバニア（首都：ティラナ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "armenia",
    "name": "アルメニア",
    "flag": "🇦🇲",
    "capital": "エレバン",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "am",
    "trivia": "【アジア】『アルメニア』をゲット！首都はエレバンだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "angola",
    "name": "アンゴラ",
    "flag": "🇦🇴",
    "capital": "ルアンダ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ao",
    "trivia": "【アフリカの国】美しいアンゴラだよ！首都はルアンダ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "austria",
    "name": "オーストリア",
    "flag": "🇦🇹",
    "capital": "ウィーン",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "at",
    "trivia": "【ヨーロッパ】大航海パズルピース『オーストリア』を発見！首都はウィーンだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "azerbaijan",
    "name": "アゼルバイジャン",
    "flag": "🇦🇿",
    "capital": "バクー",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "az",
    "trivia": "【アジアの国】アゼルバイジャン（首都：バクー）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "bosnia_and_herzegovina",
    "name": "ボスニア・ヘルツェゴビナ",
    "flag": "🇧🇦",
    "capital": "サラエボ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "ba",
    "trivia": "【ヨーロッパ】『ボスニア・ヘルツェゴビナ』をゲット！首都はサラエボだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "bangladesh",
    "name": "バングラデシュ",
    "flag": "🇧🇩",
    "capital": "ダッカ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "bd",
    "trivia": "【アジアの国】美しいバングラデシュだよ！首都はダッカ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "belgium",
    "name": "ベルギー",
    "flag": "🇧🇪",
    "capital": "ブリュッセル",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "be",
    "trivia": "【ヨーロッパ】大航海パズルピース『ベルギー』を発見！首都はブリュッセルだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "burkina_faso",
    "name": "ブルキナファソ",
    "flag": "🇧🇫",
    "capital": "ワガドゥグ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "bf",
    "trivia": "【アフリカの国】ブルキナファソ（首都：ワガドゥグ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "bulgaria",
    "name": "ブルガリア",
    "flag": "🇧🇬",
    "capital": "ソフィア",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "bg",
    "trivia": "【ヨーロッパ】『ブルガリア』をゲット！首都はソフィアだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "burundi",
    "name": "ブルンジ",
    "flag": "🇧🇮",
    "capital": "ギテガ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "bi",
    "trivia": "【アフリカの国】美しいブルンジだよ！首都はギテガ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "benin",
    "name": "ベナン",
    "flag": "🇧🇯",
    "capital": "ポルトノボ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "bj",
    "trivia": "【アフリカ】大航海パズルピース『ベナン』を発見！首都はポルトノボだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "brunei",
    "name": "ブルネイ",
    "flag": "🇧🇳",
    "capital": "バンダルスリブガワン",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "bn",
    "trivia": "【アジアの国】ブルネイ（首都：バンダルスリブガワン）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "bolivia",
    "name": "ボリビア",
    "flag": "🇧🇴",
    "capital": "スクレ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "bo",
    "trivia": "【アメリカ地域】『ボリビア』をゲット！首都はスクレだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "bahamas",
    "name": "バハマ",
    "flag": "🇧🇸",
    "capital": "ナッソー",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "bs",
    "trivia": "【アメリカ地域の国】美しいバハマだよ！首都はナッソー。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "bhutan",
    "name": "ブータン",
    "flag": "🇧🇹",
    "capital": "ティンプー",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "bt",
    "trivia": "【アジア】大航海パズルピース『ブータン』を発見！首都はティンプーだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "botswana",
    "name": "ボツワナ",
    "flag": "🇧🇼",
    "capital": "ハボローネ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "bw",
    "trivia": "【アフリカの国】ボツワナ（首都：ハボローネ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "belarus",
    "name": "ベラルーシ",
    "flag": "🇧🇾",
    "capital": "ミンスク",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "by",
    "trivia": "【ヨーロッパ】『ベラルーシ』をゲット！首都はミンスクだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "belize",
    "name": "ベリーズ",
    "flag": "🇧🇿",
    "capital": "ベルモパン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "bz",
    "trivia": "【アメリカ地域の国】美しいベリーズだよ！首都はベルモパン。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "dr_congo",
    "name": "コンゴ民主共和国",
    "flag": "🇨🇩",
    "capital": "Kinshasa",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "cd",
    "trivia": "【アフリカ】大航海パズルピース『コンゴ民主共和国』を発見！首都はKinshasaだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "central_african_republic",
    "name": "中央アフリカ",
    "flag": "🇨🇫",
    "capital": "Bangui",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "cf",
    "trivia": "【アフリカの国】中央アフリカ（首都：Bangui）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "congo",
    "name": "コンゴ共和国",
    "flag": "🇨🇬",
    "capital": "Brazzaville",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "cg",
    "trivia": "【アフリカ】『コンゴ共和国』をゲット！首都はBrazzavilleだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "ivory_coast",
    "name": "コートジボワール",
    "flag": "🇨🇮",
    "capital": "Yamoussoukro",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ci",
    "trivia": "【アフリカの国】美しいコートジボワールだよ！首都はYamoussoukro。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "chile",
    "name": "チリ",
    "flag": "🇨🇱",
    "capital": "Santiago",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "cl",
    "trivia": "【アメリカ地域】大航海パズルピース『チリ』を発見！首都はSantiagoだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "cameroon",
    "name": "カメルーン",
    "flag": "🇨🇲",
    "capital": "Yaoundé",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "cm",
    "trivia": "【アフリカの国】カメルーン（首都：Yaoundé）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "colombia",
    "name": "コロンビア",
    "flag": "🇨🇴",
    "capital": "Bogotá",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "co",
    "trivia": "【アメリカ地域】『コロンビア』をゲット！首都はBogotáだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "costa_rica",
    "name": "コスタリカ",
    "flag": "🇨🇷",
    "capital": "San José",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "cr",
    "trivia": "【アメリカ地域の国】美しいコスタリカだよ！首都はSan José。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "cuba",
    "name": "キューバ",
    "flag": "🇨🇺",
    "capital": "ハバナ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "cu",
    "trivia": "【アメリカ地域】大航海パズルピース『キューバ』を発見！首都はハバナだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "cape_verde",
    "name": "カーボベルデ",
    "flag": "🇨🇻",
    "capital": "プライア",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "cv",
    "trivia": "【アフリカの国】カーボベルデ（首都：プライア）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "cyprus",
    "name": "キプロス",
    "flag": "🇨🇾",
    "capital": "ニコシア",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "cy",
    "trivia": "【ヨーロッパ】『キプロス』をゲット！首都はニコシアだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "czechia",
    "name": "チェコ",
    "flag": "🇨🇿",
    "capital": "プラハ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "cz",
    "trivia": "【ヨーロッパの国】美しいチェコだよ！首都はプラハ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "denmark",
    "name": "デンマーク",
    "flag": "🇩🇰",
    "capital": "コペンハーゲン",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "dk",
    "trivia": "【ヨーロッパ】大航海パズルピース『デンマーク』を発見！首都はコペンハーゲンだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "djibouti",
    "name": "ジブチ",
    "flag": "🇩🇯",
    "capital": "ジブチ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "dj",
    "trivia": "【アフリカの国】ジブチ（首都：ジブチ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "dominica",
    "name": "ドミニカ国",
    "flag": "🇩🇲",
    "capital": "ロゾー",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "dm",
    "trivia": "【アメリカ地域】『ドミニカ国』をゲット！首都はロゾーだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "dominican_republic",
    "name": "ドミニカ共和国",
    "flag": "🇩🇴",
    "capital": "サントドミンゴ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "do",
    "trivia": "【アメリカ地域の国】美しいドミニカ共和国だよ！首都はサントドミンゴ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "algeria",
    "name": "アルジェリア",
    "flag": "🇩🇿",
    "capital": "アルジェ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "dz",
    "trivia": "【アフリカ】大航海パズルピース『アルジェリア』を発見！首都はアルジェだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "ecuador",
    "name": "エクアドル",
    "flag": "🇪🇨",
    "capital": "キト",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "ec",
    "trivia": "【アメリカ地域の国】エクアドル（首都：キト）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "estonia",
    "name": "エストニア",
    "flag": "🇪🇪",
    "capital": "タリン",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "ee",
    "trivia": "【ヨーロッパ】『エストニア』をゲット！首都はタリンだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "eritrea",
    "name": "エリトリア",
    "flag": "🇪🇷",
    "capital": "アスマラ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "er",
    "trivia": "【アフリカの国】美しいエリトリアだよ！首都はアスマラ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "ethiopia",
    "name": "エチオピア",
    "flag": "🇪🇹",
    "capital": "アディスアベバ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "et",
    "trivia": "【アフリカ】大航海パズルピース『エチオピア』を発見！首都はアディスアベバだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "finland",
    "name": "フィンランド",
    "flag": "🇫🇮",
    "capital": "ヘルシンキ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "fi",
    "trivia": "【ヨーロッパの国】フィンランド（首都：ヘルシンキ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "falkland_islands",
    "name": "フォークランド諸島",
    "flag": "🇫🇰",
    "capital": "スタンリー",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "fk",
    "trivia": "【アメリカ地域】『フォークランド諸島』をゲット！首都はスタンリーだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "gabon",
    "name": "ガボン",
    "flag": "🇬🇦",
    "capital": "リーブルビル",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ga",
    "trivia": "【アフリカの国】国土のなんと85%以上が豊かな熱帯雨林（ジャングル）に覆われていて、『地球の肺』とも呼ばれているよ！野生のゴリラや、海を泳ぐ珍しいカバ（サーフィンヒポ）が見られることで有名なんだ。"
  },
  {
    "id": "georgia",
    "name": "ジョージア",
    "flag": "🇬🇪",
    "capital": "トビリシ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "ge",
    "trivia": "【アジア/ヨーロッパ】8000年以上前からワイン造りを行っている『ワイン発祥の地』として知られているよ！文字も独特の丸っこくてかわいい『ジョージア文字』を使っているんだ。"
  },
  {
    "id": "ghana",
    "name": "ガーナ",
    "flag": "🇬🇭",
    "capital": "アクラ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "gh",
    "trivia": "【アフリカの国】みんなが大好きなチョコレートの原料『カカオ豆』がたくさん獲れる国だよ！世界で2番目にカカオを多く作っていて、国旗の黄色は金（ゴールド）の豊かさを表しているんだ。"
  },
  {
    "id": "gambia",
    "name": "ガンビア",
    "flag": "🇬🇲",
    "capital": "バンジュール",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "gm",
    "trivia": "【アフリカ】『ガンビア』をゲット！首都はバンジュールだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "guinea",
    "name": "ギニア",
    "flag": "🇬🇳",
    "capital": "コナクリ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "gn",
    "trivia": "【アフリカの国】美しいギニアだよ！首都はコナクリ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "equatorial_guinea",
    "name": "赤道ギニア",
    "flag": "🇬🇶",
    "capital": "マラボ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "gq",
    "trivia": "【アフリカ】大航海パズルピース『赤道ギニア』を発見！首都はマラボだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "guatemala",
    "name": "グアテマラ",
    "flag": "🇬🇹",
    "capital": "グアテマラシティ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "gt",
    "trivia": "【アメリカ地域の国】グアテマラ（首都：グアテマラシティ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "guinea_bissau",
    "name": "ギニアビサウ",
    "flag": "🇬🇼",
    "capital": "ビサウ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "gw",
    "trivia": "【アフリカ】『ギニアビサウ』をゲット！首都はビサウだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "guyana",
    "name": "ガイアナ",
    "flag": "🇬🇾",
    "capital": "ジョージタウン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "gy",
    "trivia": "【アメリカ地域の国】美しいガイアナだよ！首都はジョージタウン。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "honduras",
    "name": "ホンジュラス",
    "flag": "🇭🇳",
    "capital": "テグシガルパ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "hn",
    "trivia": "【アメリカ地域】大航海パズルピース『ホンジュラス』を発見！首都はテグシガルパだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "croatia",
    "name": "クロアチア",
    "flag": "🇭🇷",
    "capital": "ザグレブ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "hr",
    "trivia": "【ヨーロッパの国】クロアチア（首都：ザグレブ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "haiti",
    "name": "ハイチ",
    "flag": "🇭🇹",
    "capital": "ポルトープランス",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "ht",
    "trivia": "【アメリカ地域】『ハイチ』をゲット！首都はポルトープランスだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "hungary",
    "name": "ハンガリー",
    "flag": "🇭🇺",
    "capital": "ブダペスト",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "hu",
    "trivia": "【ヨーロッパの国】美しいハンガリーだよ！首都はブダペスト。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "indonesia",
    "name": "インドネシア",
    "flag": "🇮🇩",
    "capital": "ジャカルタ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "id",
    "trivia": "【アジア】大航海パズルピース『インドネシア』を発見！首都はジャカルタだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "ireland",
    "name": "アイルランド",
    "flag": "🇮🇪",
    "capital": "ダブリン",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "ie",
    "trivia": "【ヨーロッパの国】アイルランド（首都：ダブリン）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "israel",
    "name": "イスラエル",
    "flag": "🇮🇱",
    "capital": "エルサレム",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "il",
    "trivia": "【アジア】『イスラエル』をゲット！首都はエルサレムだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "iraq",
    "name": "イラク",
    "flag": "🇮🇶",
    "capital": "バグダッド",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "iq",
    "trivia": "【アジアの国】美しいイラクだよ！首都はバグダッド。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "iran",
    "name": "イラン",
    "flag": "🇮🇷",
    "capital": "テヘラン",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "ir",
    "trivia": "【アジア】大航海パズルピース『イラン』を発見！首都はテヘランだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "iceland",
    "name": "アイスランド",
    "flag": "🇮🇸",
    "capital": "レイキャビク",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "is",
    "trivia": "【ヨーロッパの国】アイスランド（首都：レイキャビク）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "jamaica",
    "name": "ジャマイカ",
    "flag": "🇯🇲",
    "capital": "キングストン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "jm",
    "trivia": "【アメリカ地域】『ジャマイカ』をゲット！首都はキングストンだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "jordan",
    "name": "ヨルダン",
    "flag": "🇯🇴",
    "capital": "アンマン",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "jo",
    "trivia": "【アジアの国】美しいヨルダンだよ！首都はアンマン。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "kyrgyzstan",
    "name": "キルギス",
    "flag": "🇰🇬",
    "capital": "ビシュケク",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "kg",
    "trivia": "【アジア】大航海パズルピース『キルギス』を発見！首都はビシュケクだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "cambodia",
    "name": "カンボジア",
    "flag": "🇰🇭",
    "capital": "プノンペン",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "kh",
    "trivia": "【アジアの国】カンボジア（首都：プノンペン）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "comoros",
    "name": "コモロ",
    "flag": "🇰🇲",
    "capital": "モロニ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "km",
    "trivia": "【アフリカ】『コモロ』をゲット！首都はモロニだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "north_korea",
    "name": "北朝鮮",
    "flag": "🇰🇵",
    "capital": "平壌",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "kp",
    "trivia": "【アジアの国】美しい北朝鮮だよ！首都は平壌。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "kuwait",
    "name": "クウェート",
    "flag": "🇰🇼",
    "capital": "クウェートシティ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "kw",
    "trivia": "【アジア】大航海パズルピース『クウェート』を発見！首都はクウェートシティだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "kazakhstan",
    "name": "カザフスタン",
    "flag": "🇰🇿",
    "capital": "アスタナ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "kz",
    "trivia": "【アジアの国】カザフスタン（首都：アスタナ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "laos",
    "name": "ラオス",
    "flag": "🇱🇦",
    "capital": "ビエンチャン",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "la",
    "trivia": "【アジア】『ラオス』をゲット！首都はビエンチャンだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "lebanon",
    "name": "レバノン",
    "flag": "🇱🇧",
    "capital": "ベイルート",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "lb",
    "trivia": "【アジアの国】美しいレバノンだよ！首都はベイルート。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "saint_lucia",
    "name": "セントルシア",
    "flag": "🇱🇨",
    "capital": "カストリーズ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "lc",
    "trivia": "【アメリカ地域】大航海パズルピース『セントルシア』を発見！首都はカストリーズだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "sri_lanka",
    "name": "スリランカ",
    "flag": "🇱🇰",
    "capital": "コロンボ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "lk",
    "trivia": "【アジアの国】スリランカ（首都：コロンボ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "liberia",
    "name": "リベリア",
    "flag": "🇱🇷",
    "capital": "モンロビア",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "lr",
    "trivia": "【アフリカ】『リベリア』をゲット！首都はモンロビアだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "lesotho",
    "name": "レソト",
    "flag": "🇱🇸",
    "capital": "マセル",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ls",
    "trivia": "【アフリカの国】美しいレソトだよ！首都はマセル。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "lithuania",
    "name": "リトアニア",
    "flag": "🇱🇹",
    "capital": "ヴィリニュス",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "lt",
    "trivia": "【ヨーロッパ】大航海パズルピース『リトアニア』を発見！首都はヴィリニュスだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "luxembourg",
    "name": "ルクセンブルク",
    "flag": "🇱🇺",
    "capital": "ルクセンブルク",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "lu",
    "trivia": "【ヨーロッパの国】ルクセンブルク（首都：ルクセンブルク）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "latvia",
    "name": "ラトビア",
    "flag": "🇱🇻",
    "capital": "リガ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "lv",
    "trivia": "【ヨーロッパ】『ラトビア』をゲット！首都はリガだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "libya",
    "name": "リビア",
    "flag": "🇱🇾",
    "capital": "トリポリ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ly",
    "trivia": "【アフリカの国】美しいリビアだよ！首都はトリポリ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "morocco",
    "name": "モロッコ",
    "flag": "🇲🇦",
    "capital": "ラバト",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ma",
    "trivia": "【アフリカ】大航海パズルピース『モロッコ』を発見！首都はラバトだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "moldova",
    "name": "モルドバ",
    "flag": "🇲🇩",
    "capital": "Chișinău",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "md",
    "trivia": "【ヨーロッパの国】モルドバ（首都：Chișinău）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "montenegro",
    "name": "モンテネグロ",
    "flag": "🇲🇪",
    "capital": "ポドゴリツァ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "me",
    "trivia": "【ヨーロッパ】『モンテネグロ』をゲット！首都はポドゴリツァだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "madagascar",
    "name": "マダガスカル",
    "flag": "🇲🇬",
    "capital": "アンタナナリボ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "mg",
    "trivia": "【アフリカの国】美しいマダガスカルだよ！首都はアンタナナリボ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "north_macedonia",
    "name": "北マケドニア",
    "flag": "🇲🇰",
    "capital": "スコピエ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "mk",
    "trivia": "【ヨーロッパ】大航海パズルピース『北マケドニア』を発見！首都はスコピエだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "mali",
    "name": "マリ",
    "flag": "🇲🇱",
    "capital": "バマコ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ml",
    "trivia": "【アフリカの国】マリ（首都：バマコ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "myanmar",
    "name": "ミャンマー",
    "flag": "🇲🇲",
    "capital": "ネピドー",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "mm",
    "trivia": "【アジア】『ミャンマー』をゲット！首都はネピドーだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "mauritania",
    "name": "モーリタニア",
    "flag": "🇲🇷",
    "capital": "ヌアクショット",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "mr",
    "trivia": "【アフリカの国】美しいモーリタニアだよ！首都はヌアクショット。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "malta",
    "name": "マルタ",
    "flag": "🇲🇹",
    "capital": "バレッタ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "mt",
    "trivia": "【ヨーロッパ】大航海パズルピース『マルタ』を発見！首都はバレッタだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "mauritius",
    "name": "モーリシャス",
    "flag": "🇲🇺",
    "capital": "ポートルイス",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "mu",
    "trivia": "【アフリカの国】モーリシャス（首都：ポートルイス）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "maldives",
    "name": "モルディブ",
    "flag": "🇲🇻",
    "capital": "マレ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "mv",
    "trivia": "【アジア】『モルディブ』をゲット！首都はマレだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "malawi",
    "name": "マラウイ",
    "flag": "🇲🇼",
    "capital": "リロングウェ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "mw",
    "trivia": "【アフリカの国】美しいマラウイだよ！首都はリロングウェ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "malaysia",
    "name": "マレーシア",
    "flag": "🇲🇾",
    "capital": "クアラルンプール",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "my",
    "trivia": "【アジア】大航海パズルピース『マレーシア』を発見！首都はクアラルンプールだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "mozambique",
    "name": "モザンビーク",
    "flag": "🇲🇿",
    "capital": "マプト",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "mz",
    "trivia": "【アフリカの国】モザンビーク（首都：マプト）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "namibia",
    "name": "ナミビア",
    "flag": "🇳🇦",
    "capital": "ウィントフック",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "na",
    "trivia": "【アフリカ】『ナミビア』をゲット！首都はウィントフックだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "new_caledonia",
    "name": "ニューカレドニア",
    "flag": "🇳🇨",
    "capital": "ヌメア",
    "region": "oceania",
    "mapX": 50,
    "mapY": 50,
    "iso": "nc",
    "trivia": "【オセアニアの国】美しいニューカレドニアだよ！首都はヌメア。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "niger",
    "name": "ニジェール",
    "flag": "🇳🇪",
    "capital": "ニアメ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ne",
    "trivia": "【アフリカ】大航海パズルピース『ニジェール』を発見！首都はニアメだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "nigeria",
    "name": "ナイジェリア",
    "flag": "🇳🇬",
    "capital": "アブジャ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ng",
    "trivia": "【アフリカの国】ナイジェリア（首都：アブジャ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "nicaragua",
    "name": "ニカラグア",
    "flag": "🇳🇮",
    "capital": "マナグア",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "ni",
    "trivia": "【アメリカ地域】『ニカラグア』をゲット！首都はマナグアだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "netherlands",
    "name": "オランダ",
    "flag": "🇳🇱",
    "capital": "アムステルダム",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "nl",
    "trivia": "【ヨーロッパの国】美しいオランダだよ！首都はアムステルダム。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "norway",
    "name": "ノルウェー",
    "flag": "🇳🇴",
    "capital": "オスロ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "no",
    "trivia": "【ヨーロッパ】大航海パズルピース『ノルウェー』を発見！首都はオスロだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "nepal",
    "name": "ネパール",
    "flag": "🇳🇵",
    "capital": "カトマンズ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "np",
    "trivia": "【アジアの国】ネパール（首都：カトマンズ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "oman",
    "name": "オマーン",
    "flag": "🇴🇲",
    "capital": "マスカット",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "om",
    "trivia": "【アジア】『オマーン』をゲット！首都はマスカットだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "panama",
    "name": "パナマ",
    "flag": "🇵🇦",
    "capital": "パナマシティ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "pa",
    "trivia": "【アメリカ地域の国】美しいパナマだよ！首都はパナマシティ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "peru",
    "name": "ペルー",
    "flag": "🇵🇪",
    "capital": "リマ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "pe",
    "trivia": "【アメリカ地域】大航海パズルピース『ペルー』を発見！首都はリマだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "papua_new_guinea",
    "name": "パプアニューギニア",
    "flag": "🇵🇬",
    "capital": "ポートモレスビー",
    "region": "oceania",
    "mapX": 50,
    "mapY": 50,
    "iso": "pg",
    "trivia": "【オセアニアの国】パプアニューギニア（首都：ポートモレスビー）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "philippines",
    "name": "フィリピン",
    "flag": "🇵🇭",
    "capital": "マニラ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "ph",
    "trivia": "【アジア】『フィリピン』をゲット！首都はマニラだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "pakistan",
    "name": "パキスタン",
    "flag": "🇵🇰",
    "capital": "イスラマバード",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "pk",
    "trivia": "【アジアの国】美しいパキスタンだよ！首都はイスラマバード。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "poland",
    "name": "ポーランド",
    "flag": "🇵🇱",
    "capital": "ワルシャワ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "pl",
    "trivia": "【ヨーロッパ】大航海パズルピース『ポーランド』を発見！首都はワルシャワだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "puerto_rico",
    "name": "プエルトリコ",
    "flag": "🇵🇷",
    "capital": "サンフアン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "pr",
    "trivia": "【アメリカ地域の国】プエルトリコ（首都：サンフアン）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "portugal",
    "name": "ポルトガル",
    "flag": "🇵🇹",
    "capital": "リスボン",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "pt",
    "trivia": "【ヨーロッパ】『ポルトガル』をゲット！首都はリスボンだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "paraguay",
    "name": "パラグアイ",
    "flag": "🇵🇾",
    "capital": "アスンシオン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "py",
    "trivia": "【アメリカ地域の国】美しいパラグアイだよ！首都はアスンシオン。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "qatar",
    "name": "カタール",
    "flag": "🇶🇦",
    "capital": "ドーハ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "qa",
    "trivia": "【アジア】大航海パズルピース『カタール』を発見！首都はドーハだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "romania",
    "name": "ルーマニア",
    "flag": "🇷🇴",
    "capital": "ブカレスト",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "ro",
    "trivia": "【ヨーロッパの国】ルーマニア（首都：ブカレスト）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "serbia",
    "name": "セルビア",
    "flag": "🇷🇸",
    "capital": "ベオグラード",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "rs",
    "trivia": "【ヨーロッパ】『セルビア』をゲット！首都はベオグラードだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "rwanda",
    "name": "ルワンダ",
    "flag": "🇷🇼",
    "capital": "キガリ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "rw",
    "trivia": "【アフリカの国】美しいルワンダだよ！首都はキガリ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "solomon_islands",
    "name": "ソロモン諸島",
    "flag": "🇸🇧",
    "capital": "ホニアラ",
    "region": "oceania",
    "mapX": 50,
    "mapY": 50,
    "iso": "sb",
    "trivia": "【オセアニア】大航海パズルピース『ソロモン諸島』を発見！首都はホニアラだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "seychelles",
    "name": "セーシェル",
    "flag": "🇸🇨",
    "capital": "ビクトリア",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "sc",
    "trivia": "【アフリカの国】セーシェル（首都：ビクトリア）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "sudan",
    "name": "スーダン",
    "flag": "🇸🇩",
    "capital": "ハルツーム",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "sd",
    "trivia": "【アフリカ】『スーダン』をゲット！首都はハルツームだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "sweden",
    "name": "スウェーデン",
    "flag": "🇸🇪",
    "capital": "ストックホルム",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "se",
    "trivia": "【ヨーロッパの国】美しいスウェーデンだよ！首都はストックホルム。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "slovenia",
    "name": "スロベニア",
    "flag": "🇸🇮",
    "capital": "リュブリャナ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "si",
    "trivia": "【ヨーロッパ】大航海パズルピース『スロベニア』を発見！首都はリュブリャナだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "slovakia",
    "name": "スロバキア",
    "flag": "🇸🇰",
    "capital": "ブラチスラバ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "sk",
    "trivia": "【ヨーロッパの国】スロバキア（首都：ブラチスラバ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "sierra_leone",
    "name": "シエラレオネ",
    "flag": "🇸🇱",
    "capital": "フリータウン",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "sl",
    "trivia": "【アフリカ】『シエラレオネ』をゲット！首都はフリータウンだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "senegal",
    "name": "セネガル",
    "flag": "🇸🇳",
    "capital": "ダカール",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "sn",
    "trivia": "【アフリカの国】美しいセネガルだよ！首都はダカール。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "somalia",
    "name": "ソマリア",
    "flag": "🇸🇴",
    "capital": "モガディシュ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "so",
    "trivia": "【アフリカ】大航海パズルピース『ソマリア』を発見！首都はモガディシュだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "suriname",
    "name": "スリナム",
    "flag": "🇸🇷",
    "capital": "パラマリボ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "sr",
    "trivia": "【アメリカ地域の国】スリナム（首都：パラマリボ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "south_sudan",
    "name": "南スーダン",
    "flag": "🇸🇸",
    "capital": "ジュバ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ss",
    "trivia": "【アフリカ】『南スーダン』をゲット！首都はジュバだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "s_o_tom_and_pr_ncipe",
    "name": "サントメ・プリンシペ",
    "flag": "🇸🇹",
    "capital": "サントメ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "st",
    "trivia": "【アフリカの国】美しいサントメ・プリンシペだよ！首都はサントメ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "el_salvador",
    "name": "エルサルバドル",
    "flag": "🇸🇻",
    "capital": "サンサルバドル",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "sv",
    "trivia": "【アメリカ地域】大航海パズルピース『エルサルバドル』を発見！首都はサンサルバドルだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "syria",
    "name": "シリア",
    "flag": "🇸🇾",
    "capital": "ダマスカス",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "sy",
    "trivia": "【アジアの国】シリア（首都：ダマスカス）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "eswatini",
    "name": "エスワティニ",
    "flag": "🇸🇿",
    "capital": "Lobamba",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "sz",
    "trivia": "【アフリカ】『エスワティニ』をゲット！首都はLobambaだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "chad",
    "name": "チャド",
    "flag": "🇹🇩",
    "capital": "ンジャメナ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "td",
    "trivia": "【アフリカの国】美しいチャドだよ！首都はンジャメナ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "togo",
    "name": "トーゴ",
    "flag": "🇹🇬",
    "capital": "ロメ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "tg",
    "trivia": "【アフリカ】大航海パズルピース『トーゴ』を発見！首都はロメだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "thailand",
    "name": "タイ",
    "flag": "🇹🇭",
    "capital": "バンコク",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "th",
    "trivia": "【アジアの国】タイ（首都：バンコク）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "tajikistan",
    "name": "タジキスタン",
    "flag": "🇹🇯",
    "capital": "ドゥシャンベ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "tj",
    "trivia": "【アジア】『タジキスタン』をゲット！首都はドゥシャンベだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "turkmenistan",
    "name": "トルクメニスタン",
    "flag": "🇹🇲",
    "capital": "アシガバート",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "tm",
    "trivia": "【アジアの国】美しいトルクメニスタンだよ！首都はアシガバート。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "tunisia",
    "name": "チュニジア",
    "flag": "🇹🇳",
    "capital": "チュニス",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "tn",
    "trivia": "【アフリカ】大航海パズルピース『チュニジア』を発見！首都はチュニスだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "trinidad_and_tobago",
    "name": "トリニダード・トバゴ",
    "flag": "🇹🇹",
    "capital": "ポートオブスペイン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "tt",
    "trivia": "【アメリカ地域の国】トリニダード・トバゴ（首都：ポートオブスペイン）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "tanzania",
    "name": "タンザニア",
    "flag": "🇹🇿",
    "capital": "ドドマ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "tz",
    "trivia": "【アフリカ】『タンザニア』をゲット！首都はドドマだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "ukraine",
    "name": "ウクライナ",
    "flag": "🇺🇦",
    "capital": "キエフ",
    "region": "europe",
    "mapX": 50,
    "mapY": 50,
    "iso": "ua",
    "trivia": "【ヨーロッパの国】美しいウクライナだよ！首都はキエフ。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "uganda",
    "name": "ウガンダ",
    "flag": "🇺🇬",
    "capital": "カンパラ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "ug",
    "trivia": "【アフリカ】大航海パズルピース『ウガンダ』を発見！首都はカンパラだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "uruguay",
    "name": "ウルグアイ",
    "flag": "🇺🇾",
    "capital": "モンテビデオ",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "uy",
    "trivia": "【アメリカ地域の国】ウルグアイ（首都：モンテビデオ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "uzbekistan",
    "name": "ウズベキスタン",
    "flag": "🇺🇿",
    "capital": "タシュケント",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "uz",
    "trivia": "【アジア】『ウズベキスタン』をゲット！首都はタシュケントだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "saint_vincent_and_the_grenadines",
    "name": "セントビンセント・グレナディーン",
    "flag": "🇻🇨",
    "capital": "キングスタウン",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "vc",
    "trivia": "【アメリカ地域の国】美しいセントビンセント・グレナディーンだよ！首都はキングスタウン。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "venezuela",
    "name": "ベネズエラ",
    "flag": "🇻🇪",
    "capital": "カラカス",
    "region": "americas",
    "mapX": 50,
    "mapY": 50,
    "iso": "ve",
    "trivia": "【アメリカ地域】大航海パズルピース『ベネズエラ』を発見！首都はカラカスだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "vietnam",
    "name": "ベトナム",
    "flag": "🇻🇳",
    "capital": "ハノイ",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "vn",
    "trivia": "【アジアの国】ベトナム（首都：ハノイ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "vanuatu",
    "name": "バヌアツ",
    "flag": "🇻🇺",
    "capital": "ポートビラ",
    "region": "oceania",
    "mapX": 50,
    "mapY": 50,
    "iso": "vu",
    "trivia": "【オセアニア】『バヌアツ』をゲット！首都はポートビラだよ。世界の国々を全部集めて世界地図を完成させよう！"
  },
  {
    "id": "yemen",
    "name": "イエメン",
    "flag": "🇾🇪",
    "capital": "Sana'a",
    "region": "asia",
    "mapX": 50,
    "mapY": 50,
    "iso": "ye",
    "trivia": "【アジアの国】美しいイエメンだよ！首都はSana'a。パズルを正しくはめて、大航海をさらに進めよう！"
  },
  {
    "id": "zambia",
    "name": "ザンビア",
    "flag": "🇿🇲",
    "capital": "ルサカ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "zm",
    "trivia": "【アフリカ】大航海パズルピース『ザンビア』を発見！首都はルサカだよ。どんな冒険が待っているかな？"
  },
  {
    "id": "zimbabwe",
    "name": "ジンバブエ",
    "flag": "🇿🇼",
    "capital": "ハラレ",
    "region": "africa",
    "mapX": 50,
    "mapY": 50,
    "iso": "zw",
    "trivia": "【アフリカの国】ジンバブエ（首都：ハラレ）だよ。世界地図パズルを完成させて、ゴールドショップでModをガチャろう！"
  },
  {
    "id": "andorra",
    "name": "アンドラ",
    "flag": "🇦🇩",
    "capital": "アンドラ・ラ・ベラ",
    "region": "europe",
    "mapX": 46.5,
    "mapY": 32.5,
    "iso": null,
    "trivia": "フランスとスペインの間にあるピレネー山脈の中にある小さな国。スノーボードやスキーなどのウィンタースポーツが盛んだよ！"
  },
  {
    "id": "antigua_and_barbuda",
    "name": "アンティグア・バーブーダ",
    "flag": "🇦🇬",
    "capital": "セントジョンズ",
    "region": "americas",
    "mapX": 22,
    "mapY": 49,
    "iso": null,
    "trivia": "カリブ海に浮かぶ美しい島国。オバマ大統領の名前がついた山があるなど、365個もの白い砂浜ビーチが有名だよ！"
  },
  {
    "id": "bahrain",
    "name": "バーレーン",
    "flag": "🇧🇭",
    "capital": "マナマ",
    "region": "asia",
    "mapX": 60.5,
    "mapY": 46.5,
    "iso": null,
    "trivia": "ペルシャ湾にある島国で、「２つの海」という意味を持つ国。F1グランプリ（カーレース）が開催されるハイテクな国だよ！"
  },
  {
    "id": "barbados",
    "name": "バルバドス",
    "flag": "🇧🇧",
    "capital": "ブリッジタウン",
    "region": "americas",
    "mapX": 23,
    "mapY": 51,
    "iso": null,
    "trivia": "カリブ海の島国で、ラム酒発祥の地として知られているよ。世界的に有名な歌手リアーナの出身国でもあるんだ！"
  },
  {
    "id": "fiji",
    "name": "フィジー",
    "flag": "🇫🇯",
    "capital": "スバ",
    "region": "oceania",
    "mapX": 92,
    "mapY": 72,
    "iso": null,
    "trivia": "南太平洋にある300以上の島からなる国。ラグビーが国技で、人々がとてもフレンドリーで幸せな国として有名だよ！"
  },
  {
    "id": "micronesia",
    "name": "ミクロネシア",
    "flag": "🇫🇲",
    "capital": "パリキール",
    "region": "oceania",
    "mapX": 88,
    "mapY": 58,
    "iso": null,
    "trivia": "太平洋にある600以上の島からなる連邦国。ジープ島など美しいダイビングスポットがあり、イルカと泳げるよ！"
  },
  {
    "id": "grenada",
    "name": "グレナダ",
    "flag": "🇬🇩",
    "capital": "セントジョージズ",
    "region": "americas",
    "mapX": 22,
    "mapY": 52,
    "iso": null,
    "trivia": "カリブ海の島国で、「スパイスの島」と呼ばれるほどナツメグやシナモンなどの香辛料の生産が盛んだよ！"
  },
  {
    "id": "kiribati",
    "name": "キリバス",
    "flag": "🇰🇮",
    "capital": "タラワ",
    "region": "oceania",
    "mapX": 95,
    "mapY": 62,
    "iso": null,
    "trivia": "太平洋に広がるたくさんの環礁からなる国。世界で一番早く新しい一日（朝）が始まる国でもあるんだ！"
  },
  {
    "id": "saint_kitts_and_nevis",
    "name": "セントキッツ・ネイビス",
    "flag": "🇰🇳",
    "capital": "バステール",
    "region": "americas",
    "mapX": 21.5,
    "mapY": 49.5,
    "iso": null,
    "trivia": "カリブ海にある2つの島からなる国。カリブ海で最も古いヨーロッパ人の入植地があり、サトウキビの鉄道が走っているよ！"
  },
  {
    "id": "liechtenstein",
    "name": "リヒテンシュタイン",
    "flag": "🇱🇮",
    "capital": "ファドゥーツ",
    "region": "europe",
    "mapX": 48.5,
    "mapY": 30.5,
    "iso": null,
    "trivia": "スイスとオーストリアに囲まれた、世界で唯一国名が侯爵家の姓になっている国。切手の発行が世界的にも有名だよ！"
  },
  {
    "id": "monaco",
    "name": "モナコ",
    "flag": "🇲🇨",
    "capital": "モナコ",
    "region": "europe",
    "mapX": 47.5,
    "mapY": 32.8,
    "iso": null,
    "trivia": "世界で2番目に面積が小さい、地中海に面した非常に裕福な都市国家。モナコF1グランプリやカジノが有名だよ！"
  },
  {
    "id": "marshall_islands",
    "name": "マーシャル諸島",
    "flag": "🇲🇭",
    "capital": "マジュロ",
    "region": "oceania",
    "mapX": 89,
    "mapY": 55,
    "iso": null,
    "trivia": "「太平洋の真珠」と呼ばれる美しい環礁の国。伝統的な航海技術（スティックチャートという波の海図）が有名だよ！"
  },
  {
    "id": "nauru",
    "name": "ナウル",
    "flag": "🇳🇷",
    "capital": "ヤレン",
    "region": "oceania",
    "mapX": 90,
    "mapY": 63,
    "iso": null,
    "trivia": "世界で最も小さい島国の一つ。サンゴ礁の化石からできた「アホウドリのフン」の堆積によってリン鉱石が豊富だったよ！"
  },
  {
    "id": "palau",
    "name": "パラオ",
    "flag": "🇵🇼",
    "capital": "マルキョク",
    "region": "oceania",
    "mapX": 83,
    "mapY": 57,
    "iso": null,
    "trivia": "日本と歴史的に深くつながっており、日本語由来の言葉が多い島国。クラゲと一緒に泳げるジェリーフィッシュレイクがあるよ！"
  },
  {
    "id": "san_marino",
    "name": "サンマリノ",
    "flag": "🇸🇲",
    "capital": "サンマリノ",
    "region": "europe",
    "mapX": 49.2,
    "mapY": 32.8,
    "iso": null,
    "trivia": "イタリアに囲まれた、世界で最も古い現存する共和国。ティターノ山頂に立つ3つの塔の要塞がとてもカッコいいよ！"
  },
  {
    "id": "timor_leste",
    "name": "東ティモール",
    "flag": "🇹🇱",
    "capital": "ディリ",
    "region": "asia",
    "mapX": 80,
    "mapY": 61,
    "iso": null,
    "trivia": "21世紀最初に独立したアジアの国。美しいサンゴ礁があり、美味しい高級コーヒー（フェアトレード）が日本でも人気だよ！"
  },
  {
    "id": "tonga",
    "name": "トンガ",
    "flag": "🇹🇴",
    "capital": "ヌクアロファ",
    "region": "oceania",
    "mapX": 91,
    "mapY": 77,
    "iso": null,
    "trivia": "南太平洋にあるポリネシアの王国。王室が存在し、ラグビーが盛んで選手たちの伝統のウォークライ（シピタウ）が迫力満点！"
  },
  {
    "id": "tuvalu",
    "name": "ツバル",
    "flag": "🇹🇻",
    "capital": "フナフティ",
    "region": "oceania",
    "mapX": 91,
    "mapY": 67,
    "iso": null,
    "trivia": "温暖化による海面上昇で「水没する危機にある国」として有名な、サンゴ礁の島々からなる小さな美しい国だよ！"
  },
  {
    "id": "samoa",
    "name": "サモア",
    "flag": "🇼🇸",
    "capital": "アピア",
    "region": "oceania",
    "mapX": 92,
    "mapY": 73,
    "iso": null,
    "trivia": "タトゥー（入れ墨）の語源となった「タタウ」の伝統があるポリネシアの島国。ラグビーや独特の踊りササが有名だよ！"
  }
];
